name: dokani_bahe
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  assets:
      - assets/images/shop.png
      - assets/images/bakcround.png
      - assets/images/bag.jpg
      - assets/images/bage.jpg
      - assets/images/re.png
      - assets/images/


